"""
This type stub file was generated by pyright.
"""

import pkgutil
from .filters import *
from .filterset import FilterSet
from . import rest_framework

if pkgutil.find_loader('rest_framework') is not None:
    ...
__version__ = ...
def parse_version(version): # -> tuple[Unknown, ...]:
    '''
    '0.1.2.dev1' -> (0, 1, 2, ''''
    ...

VERSION = ...
