# Generated by Django 4.0.3 on 2022-04-08 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_finance_init'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financecategory',
            unique_together={('user', 'title')},
        ),
    ]
