"""
This type stub file was generated by pyright.
"""

class Range:
    ...


class NumericRange(Range):
    ...


class DateRange(Range):
    ...


class DateTimeRange(Range):
    ...


class DateTimeTZRange(Range):
    ...


