"""
This type stub file was generated by pyright.
"""

from rest_framework import exceptions

class TokenError(Exception):
    ...


class TokenBackendError(Exception):
    ...


class DetailDictMixin:
    def __init__(self, detail=..., code=...) -> None:
        """
        Builds a detail diction"""
        ...
    


class AuthenticationFailed(DetailDictMixin, exceptions.AuthenticationFailed):
    ...


class InvalidToken(AuthenticationFailed):
    status_code = ...
    default_detail = ...
    default_code = ...


