"""
This type stub file was generated by pyright.
"""

def make_utc(dt): # -> datetime:
    ...

def aware_utcnow(): # -> datetime:
    ...

def datetime_to_epoch(dt): # -> int:
    ...

def datetime_from_epoch(ts): # -> datetime:
    ...

def format_lazy(s, *args, **kwargs):
    ...

format_lazy = ...
