"""
This type stub file was generated by pyright.
"""

from rest_framework import generics

class TokenViewBase(generics.GenericAPIView):
    permission_classes = ...
    authentication_classes = ...
    serializer_class = ...
    _serializer_class = ...
    www_authenticate_realm = ...
    def get_serializer_class(self): # -> Any:
        """
        If serializer_class is """
        ...
    
    def get_authenticate_header(self, request): # -> str:
        ...
    
    def post(self, request, *args, **kwargs): # -> Response:
        ...
    


class TokenObtainPairView(TokenViewBase):
    """
    Takes a set of user credent"""
    _serializer_class = ...


token_obtain_pair = ...
class TokenRefreshView(TokenViewBase):
    """
    Takes a refresh type JSON w"""
    _serializer_class = ...


token_refresh = ...
class TokenObtainSlidingView(TokenViewBase):
    """
    Takes a set of user credent"""
    _serializer_class = ...


token_obtain_sliding = ...
class TokenRefreshSlidingView(TokenViewBase):
    """
    Takes a sliding JSON web to"""
    _serializer_class = ...


token_refresh_sliding = ...
class TokenVerifyView(TokenViewBase):
    """
    Takes a token and indicates"""
    _serializer_class = ...


token_verify = ...
class TokenBlacklistView(TokenViewBase):
    """
    Takes a token and blacklist"""
    _serializer_class = ...


token_blacklist = ...
