"""
This type stub file was generated by pyright.
"""

from django.utils.deprecation import RenameMethodsBase
from .. import utils
from . import filterset

class RenameAttributes(utils.RenameAttributesBase, RenameMethodsBase):
    renamed_attributes = ...
    renamed_methods = ...


class DjangoFilterBackend(metaclass=RenameAttributes):
    filterset_base = filterset.FilterSet
    raise_exception = ...
    @property
    def template(self): # -> Literal['django_filters/rest_framework/crispy_form.html', 'django_filters/rest_framework/form.html']:
        ...
    
    def get_filterset(self, request, queryset, view): # -> None:
        ...
    
    def get_filterset_class(self, view, queryset=...):
        """
        Return the `FilterSet` """
        ...
    
    def get_filterset_kwargs(self, request, queryset, view): # -> dict[str, Unknown]:
        ...
    
    def filter_queryset(self, request, queryset, view):
        ...
    
    def to_html(self, request, queryset, view): # -> Any | None:
        ...
    
    def get_coreschema_field(self, field): # -> Number | String:
        ...
    
    def get_schema_fields(self, view): # -> list[Field]:
        ...
    
    def get_schema_operation_parameters(self, view): # -> list[Unknown]:
        ...
    


