"""
This type stub file was generated by pyright.
"""

import os
import re
import sys
import warnings

__version__ = ...
line_re = ...
variable_re = ...

def read_dotenv(dotenv=..., override=...) -> None:
    """
    Read a .env file into os.en"""
    ...

def parse_dotenv(content): ...
