"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable

def unbool(element: Any, true: Any = ..., false: Any = ...) -> Any:
    ...

def uniq(container: Iterable[object]) -> bool:
    ...

